---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 11/16/2025 2:29 PM
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 10/18/2025 2:29 PM
---

return function(player, level)
    for i = 1, 65 do
        local ironStack = getItemStack("minecraft:iron_ingot")
        player:getInventory():add(ironStack)
    end
    player:giveExperiencePoints(10)
end