---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Hanzo.
--- DateTime: 11/16/2025 2:26 PM
---

return function(player, quest, stage)
    local result = hasKilledEntity(player, "minecraft:pillager")

    return result.killed and result.count >= 5
end